// Code generated by internal/gen. DO NOT EDIT.

package zerodecimal

// pow10Tab holds the reciprocal-division constants for 10^k, k = 0..19
// (see pow10Entry). It is sized 32 so pow10Tab[k&31] compiles without a
// bounds check; entries 20..31 stay zero and are unreachable under the
// documented k ≤ MaxPrec preconditions.
var pow10Tab = [32]pow10Entry{
	// k = 0: m and p are zero because they are unused —
	// every divmod path short-circuits k == 0 before the lookup.
	{d: 1, m: 0x0000000000000000, dn: 0x8000000000000000, v: 0xffffffffffffffff, p: 0, s: 63},                    // k = 0
	{d: 10, m: 0xcccccccccccccccd, dn: 0xa000000000000000, v: 0x9999999999999999, p: 2, s: 60},                   // k = 1
	{d: 100, m: 0x51eb851eb851eb86, dn: 0xc800000000000000, v: 0x47ae147ae147ae14, p: 3, s: 57},                  // k = 2
	{d: 1000, m: 0x20c49ba5e353f7cf, dn: 0xfa00000000000000, v: 0x0624dd2f1a9fbe76, p: 4, s: 54},                 // k = 3
	{d: 10000, m: 0x1a36e2eb1c432ca6, dn: 0x9c40000000000000, v: 0xa36e2eb1c432ca57, p: 6, s: 50},                // k = 4
	{d: 100000, m: 0x0a7c5ac471b47843, dn: 0xc350000000000000, v: 0x4f8b588e368f0846, p: 7, s: 47},               // k = 5
	{d: 1000000, m: 0x0431bde82d7b634e, dn: 0xf424000000000000, v: 0x0c6f7a0b5ed8d36b, p: 8, s: 44},              // k = 6
	{d: 10000000, m: 0x035afe535795e90b, dn: 0x9896800000000000, v: 0xad7f29abcaf48578, p: 10, s: 40},            // k = 7
	{d: 100000000, m: 0x015798ee2308c39e, dn: 0xbebc200000000000, v: 0x5798ee2308c39df9, p: 11, s: 37},           // k = 8
	{d: 1000000000, m: 0x0089705f4136b4a6, dn: 0xee6b280000000000, v: 0x12e0be826d694b2e, p: 12, s: 34},          // k = 9
	{d: 10000000000, m: 0x006df37f675ef6eb, dn: 0x9502f90000000000, v: 0xb7cdfd9d7bdbab7d, p: 14, s: 30},         // k = 10
	{d: 100000000000, m: 0x002bfaffc2f2c92b, dn: 0xba43b74000000000, v: 0x5fd7fe17964955fd, p: 15, s: 27},        // k = 11
	{d: 1000000000000, m: 0x00119799812dea12, dn: 0xe8d4a51000000000, v: 0x19799812dea11197, p: 16, s: 24},       // k = 12
	{d: 10000000000000, m: 0x000e12e13424bb41, dn: 0x9184e72a00000000, v: 0xc25c268497681c26, p: 18, s: 20},      // k = 13
	{d: 100000000000000, m: 0x0005a126e1a84ae7, dn: 0xb5e620f480000000, v: 0x6849b86a12b9b01e, p: 19, s: 17},     // k = 14
	{d: 1000000000000000, m: 0x00024075f3dceac3, dn: 0xe35fa931a0000000, v: 0x203af9ee756159b2, p: 20, s: 14},    // k = 15
	{d: 10000000000000000, m: 0x0001cd2b297d889c, dn: 0x8e1bc9bf04000000, v: 0xcd2b297d889bc2b6, p: 22, s: 10},   // k = 16
	{d: 100000000000000000, m: 0x0000b877aa3236a5, dn: 0xb1a2bc2ec5000000, v: 0x70ef54646d496892, p: 23, s: 7},   // k = 17
	{d: 1000000000000000000, m: 0x000049c97747490f, dn: 0xde0b6b3a76400000, v: 0x2725dd1d243aba0e, p: 24, s: 4},  // k = 18
	{d: 10000000000000000000, m: 0x00003b07929f6da6, dn: 0x8ac7230489e80000, v: 0xd83c94fb6d2ac34a, p: 26, s: 0}, // k = 19
}

// pow10u64 holds 10^k for k = 0..19; entries 20..31 stay zero, padding the
// array to a power of two for bounds-check-free indexing.
var pow10u64 = [32]uint64{
	1,                    // 10^0
	10,                   // 10^1
	100,                  // 10^2
	1000,                 // 10^3
	10000,                // 10^4
	100000,               // 10^5
	1000000,              // 10^6
	10000000,             // 10^7
	100000000,            // 10^8
	1000000000,           // 10^9
	10000000000,          // 10^10
	100000000000,         // 10^11
	1000000000000,        // 10^12
	10000000000000,       // 10^13
	100000000000000,      // 10^14
	1000000000000000,     // 10^15
	10000000000000000,    // 10^16
	100000000000000000,   // 10^17
	1000000000000000000,  // 10^18
	10000000000000000000, // 10^19
}

// pow10u128 holds 10^k for k = 0..38 — the full range of precision-product
// scale factors; entries 39..63 stay zero, padding the array to a power of
// two for bounds-check-free indexing.
var pow10u128 = [64]u128{
	{lo: 1},                    // 10^0
	{lo: 10},                   // 10^1
	{lo: 100},                  // 10^2
	{lo: 1000},                 // 10^3
	{lo: 10000},                // 10^4
	{lo: 100000},               // 10^5
	{lo: 1000000},              // 10^6
	{lo: 10000000},             // 10^7
	{lo: 100000000},            // 10^8
	{lo: 1000000000},           // 10^9
	{lo: 10000000000},          // 10^10
	{lo: 100000000000},         // 10^11
	{lo: 1000000000000},        // 10^12
	{lo: 10000000000000},       // 10^13
	{lo: 100000000000000},      // 10^14
	{lo: 1000000000000000},     // 10^15
	{lo: 10000000000000000},    // 10^16
	{lo: 100000000000000000},   // 10^17
	{lo: 1000000000000000000},  // 10^18
	{lo: 10000000000000000000}, // 10^19
	{hi: 0x0000000000000005, lo: 0x6bc75e2d63100000}, // 10^20
	{hi: 0x0000000000000036, lo: 0x35c9adc5dea00000}, // 10^21
	{hi: 0x000000000000021e, lo: 0x19e0c9bab2400000}, // 10^22
	{hi: 0x000000000000152d, lo: 0x02c7e14af6800000}, // 10^23
	{hi: 0x000000000000d3c2, lo: 0x1bcecceda1000000}, // 10^24
	{hi: 0x0000000000084595, lo: 0x161401484a000000}, // 10^25
	{hi: 0x000000000052b7d2, lo: 0xdcc80cd2e4000000}, // 10^26
	{hi: 0x00000000033b2e3c, lo: 0x9fd0803ce8000000}, // 10^27
	{hi: 0x00000000204fce5e, lo: 0x3e25026110000000}, // 10^28
	{hi: 0x00000001431e0fae, lo: 0x6d7217caa0000000}, // 10^29
	{hi: 0x0000000c9f2c9cd0, lo: 0x4674edea40000000}, // 10^30
	{hi: 0x0000007e37be2022, lo: 0xc0914b2680000000}, // 10^31
	{hi: 0x000004ee2d6d415b, lo: 0x85acef8100000000}, // 10^32
	{hi: 0x0000314dc6448d93, lo: 0x38c15b0a00000000}, // 10^33
	{hi: 0x0001ed09bead87c0, lo: 0x378d8e6400000000}, // 10^34
	{hi: 0x0013426172c74d82, lo: 0x2b878fe800000000}, // 10^35
	{hi: 0x00c097ce7bc90715, lo: 0xb34b9f1000000000}, // 10^36
	{hi: 0x0785ee10d5da46d9, lo: 0x00f436a000000000}, // 10^37
	{hi: 0x4b3b4ca85a86c47a, lo: 0x098a224000000000}, // 10^38
}

// dboxPow10Min/dboxPow10Max bound dboxPow10: the Dragonbox shortest-digit
// core (dbox.go) requests decimal exponents k in [-31, 37] over the
// NewFromFloat guarded domain, and the table covers a safe superset so no
// lookup dboxPow10[k-dboxPow10Min] can index out of range.
const (
	dboxPow10Min = -40
	dboxPow10Max = 48
)

// dboxPow10 holds the 128-bit Dragonbox φ̃k mantissas of 10^k for
// k = -40..48, normalized so the high bit is always set (no implicit leading
// 1 bit). float32 conversion uses the high 64 bits only. Bit-identical to
// Go 1.26's strconv pow10Tab over this range.
var dboxPow10 = [89]u128{
	{hi: 0x8b61313bbabce2c6, lo: 0x2323ac4b3b3da015}, // 10^-40
	{hi: 0xae397d8aa96c1b77, lo: 0xabec975e0a0d081a}, // 10^-39
	{hi: 0xd9c7dced53c72255, lo: 0x96e7bd358c904a21}, // 10^-38
	{hi: 0x881cea14545c7575, lo: 0x7e50d64177da2e54}, // 10^-37
	{hi: 0xaa242499697392d2, lo: 0xdde50bd1d5d0b9e9}, // 10^-36
	{hi: 0xd4ad2dbfc3d07787, lo: 0x955e4ec64b44e864}, // 10^-35
	{hi: 0x84ec3c97da624ab4, lo: 0xbd5af13bef0b113e}, // 10^-34
	{hi: 0xa6274bbdd0fadd61, lo: 0xecb1ad8aeacdd58e}, // 10^-33
	{hi: 0xcfb11ead453994ba, lo: 0x67de18eda5814af2}, // 10^-32
	{hi: 0x81ceb32c4b43fcf4, lo: 0x80eacf948770ced7}, // 10^-31
	{hi: 0xa2425ff75e14fc31, lo: 0xa1258379a94d028d}, // 10^-30
	{hi: 0xcad2f7f5359a3b3e, lo: 0x096ee45813a04330}, // 10^-29
	{hi: 0xfd87b5f28300ca0d, lo: 0x8bca9d6e188853fc}, // 10^-28
	{hi: 0x9e74d1b791e07e48, lo: 0x775ea264cf55347d}, // 10^-27
	{hi: 0xc612062576589dda, lo: 0x95364afe032a819d}, // 10^-26
	{hi: 0xf79687aed3eec551, lo: 0x3a83ddbd83f52204}, // 10^-25
	{hi: 0x9abe14cd44753b52, lo: 0xc4926a9672793542}, // 10^-24
	{hi: 0xc16d9a0095928a27, lo: 0x75b7053c0f178293}, // 10^-23
	{hi: 0xf1c90080baf72cb1, lo: 0x5324c68b12dd6338}, // 10^-22
	{hi: 0x971da05074da7bee, lo: 0xd3f6fc16ebca5e03}, // 10^-21
	{hi: 0xbce5086492111aea, lo: 0x88f4bb1ca6bcf584}, // 10^-20
	{hi: 0xec1e4a7db69561a5, lo: 0x2b31e9e3d06c32e5}, // 10^-19
	{hi: 0x9392ee8e921d5d07, lo: 0x3aff322e62439fcf}, // 10^-18
	{hi: 0xb877aa3236a4b449, lo: 0x09befeb9fad487c2}, // 10^-17
	{hi: 0xe69594bec44de15b, lo: 0x4c2ebe687989a9b3}, // 10^-16
	{hi: 0x901d7cf73ab0acd9, lo: 0x0f9d37014bf60a10}, // 10^-15
	{hi: 0xb424dc35095cd80f, lo: 0x538484c19ef38c94}, // 10^-14
	{hi: 0xe12e13424bb40e13, lo: 0x2865a5f206b06fb9}, // 10^-13
	{hi: 0x8cbccc096f5088cb, lo: 0xf93f87b7442e45d3}, // 10^-12
	{hi: 0xafebff0bcb24aafe, lo: 0xf78f69a51539d748}, // 10^-11
	{hi: 0xdbe6fecebdedd5be, lo: 0xb573440e5a884d1b}, // 10^-10
	{hi: 0x89705f4136b4a597, lo: 0x31680a88f8953030}, // 10^-9
	{hi: 0xabcc77118461cefc, lo: 0xfdc20d2b36ba7c3d}, // 10^-8
	{hi: 0xd6bf94d5e57a42bc, lo: 0x3d32907604691b4c}, // 10^-7
	{hi: 0x8637bd05af6c69b5, lo: 0xa63f9a49c2c1b10f}, // 10^-6
	{hi: 0xa7c5ac471b478423, lo: 0x0fcf80dc33721d53}, // 10^-5
	{hi: 0xd1b71758e219652b, lo: 0xd3c36113404ea4a8}, // 10^-4
	{hi: 0x83126e978d4fdf3b, lo: 0x645a1cac083126e9}, // 10^-3
	{hi: 0xa3d70a3d70a3d70a, lo: 0x3d70a3d70a3d70a3}, // 10^-2
	{hi: 0xcccccccccccccccc, lo: 0xcccccccccccccccc}, // 10^-1
	{hi: 0x8000000000000000, lo: 0x0000000000000000}, // 10^0
	{hi: 0xa000000000000000, lo: 0x0000000000000000}, // 10^1
	{hi: 0xc800000000000000, lo: 0x0000000000000000}, // 10^2
	{hi: 0xfa00000000000000, lo: 0x0000000000000000}, // 10^3
	{hi: 0x9c40000000000000, lo: 0x0000000000000000}, // 10^4
	{hi: 0xc350000000000000, lo: 0x0000000000000000}, // 10^5
	{hi: 0xf424000000000000, lo: 0x0000000000000000}, // 10^6
	{hi: 0x9896800000000000, lo: 0x0000000000000000}, // 10^7
	{hi: 0xbebc200000000000, lo: 0x0000000000000000}, // 10^8
	{hi: 0xee6b280000000000, lo: 0x0000000000000000}, // 10^9
	{hi: 0x9502f90000000000, lo: 0x0000000000000000}, // 10^10
	{hi: 0xba43b74000000000, lo: 0x0000000000000000}, // 10^11
	{hi: 0xe8d4a51000000000, lo: 0x0000000000000000}, // 10^12
	{hi: 0x9184e72a00000000, lo: 0x0000000000000000}, // 10^13
	{hi: 0xb5e620f480000000, lo: 0x0000000000000000}, // 10^14
	{hi: 0xe35fa931a0000000, lo: 0x0000000000000000}, // 10^15
	{hi: 0x8e1bc9bf04000000, lo: 0x0000000000000000}, // 10^16
	{hi: 0xb1a2bc2ec5000000, lo: 0x0000000000000000}, // 10^17
	{hi: 0xde0b6b3a76400000, lo: 0x0000000000000000}, // 10^18
	{hi: 0x8ac7230489e80000, lo: 0x0000000000000000}, // 10^19
	{hi: 0xad78ebc5ac620000, lo: 0x0000000000000000}, // 10^20
	{hi: 0xd8d726b7177a8000, lo: 0x0000000000000000}, // 10^21
	{hi: 0x878678326eac9000, lo: 0x0000000000000000}, // 10^22
	{hi: 0xa968163f0a57b400, lo: 0x0000000000000000}, // 10^23
	{hi: 0xd3c21bcecceda100, lo: 0x0000000000000000}, // 10^24
	{hi: 0x84595161401484a0, lo: 0x0000000000000000}, // 10^25
	{hi: 0xa56fa5b99019a5c8, lo: 0x0000000000000000}, // 10^26
	{hi: 0xcecb8f27f4200f3a, lo: 0x0000000000000000}, // 10^27
	{hi: 0x813f3978f8940984, lo: 0x4000000000000000}, // 10^28
	{hi: 0xa18f07d736b90be5, lo: 0x5000000000000000}, // 10^29
	{hi: 0xc9f2c9cd04674ede, lo: 0xa400000000000000}, // 10^30
	{hi: 0xfc6f7c4045812296, lo: 0x4d00000000000000}, // 10^31
	{hi: 0x9dc5ada82b70b59d, lo: 0xf020000000000000}, // 10^32
	{hi: 0xc5371912364ce305, lo: 0x6c28000000000000}, // 10^33
	{hi: 0xf684df56c3e01bc6, lo: 0xc732000000000000}, // 10^34
	{hi: 0x9a130b963a6c115c, lo: 0x3c7f400000000000}, // 10^35
	{hi: 0xc097ce7bc90715b3, lo: 0x4b9f100000000000}, // 10^36
	{hi: 0xf0bdc21abb48db20, lo: 0x1e86d40000000000}, // 10^37
	{hi: 0x96769950b50d88f4, lo: 0x1314448000000000}, // 10^38
	{hi: 0xbc143fa4e250eb31, lo: 0x17d955a000000000}, // 10^39
	{hi: 0xeb194f8e1ae525fd, lo: 0x5dcfab0800000000}, // 10^40
	{hi: 0x92efd1b8d0cf37be, lo: 0x5aa1cae500000000}, // 10^41
	{hi: 0xb7abc627050305ad, lo: 0xf14a3d9e40000000}, // 10^42
	{hi: 0xe596b7b0c643c719, lo: 0x6d9ccd05d0000000}, // 10^43
	{hi: 0x8f7e32ce7bea5c6f, lo: 0xe4820023a2000000}, // 10^44
	{hi: 0xb35dbf821ae4f38b, lo: 0xdda2802c8a800000}, // 10^45
	{hi: 0xe0352f62a19e306e, lo: 0xd50b2037ad200000}, // 10^46
	{hi: 0x8c213d9da502de45, lo: 0x4526f422cc340000}, // 10^47
	{hi: 0xaf298d050e4395d6, lo: 0x9670b12b7f410000}, // 10^48
}
