// Code generated by internal/gen. DO NOT EDIT.

package zerodecimal

// pow10Tab holds the reciprocal-division constants for 10^k, k = 0..19
// (see pow10Entry). It is sized 32 so pow10Tab[k&31] compiles without a
// bounds check; entries 20..31 stay zero and are unreachable under the
// documented k ≤ MaxPrec preconditions.
var pow10Tab = [32]pow10Entry{
	// k = 0: m and p are zero because they are unused —
	// every divmod path short-circuits k == 0 before the lookup.
	{d: 1, m: 0x0000000000000000, dn: 0x8000000000000000, v: 0xffffffffffffffff, p: 0, s: 63},                    // k = 0
	{d: 10, m: 0xcccccccccccccccd, dn: 0xa000000000000000, v: 0x9999999999999999, p: 2, s: 60},                   // k = 1
	{d: 100, m: 0x51eb851eb851eb86, dn: 0xc800000000000000, v: 0x47ae147ae147ae14, p: 3, s: 57},                  // k = 2
	{d: 1000, m: 0x20c49ba5e353f7cf, dn: 0xfa00000000000000, v: 0x0624dd2f1a9fbe76, p: 4, s: 54},                 // k = 3
	{d: 10000, m: 0x1a36e2eb1c432ca6, dn: 0x9c40000000000000, v: 0xa36e2eb1c432ca57, p: 6, s: 50},                // k = 4
	{d: 100000, m: 0x0a7c5ac471b47843, dn: 0xc350000000000000, v: 0x4f8b588e368f0846, p: 7, s: 47},               // k = 5
	{d: 1000000, m: 0x0431bde82d7b634e, dn: 0xf424000000000000, v: 0x0c6f7a0b5ed8d36b, p: 8, s: 44},              // k = 6
	{d: 10000000, m: 0x035afe535795e90b, dn: 0x9896800000000000, v: 0xad7f29abcaf48578, p: 10, s: 40},            // k = 7
	{d: 100000000, m: 0x015798ee2308c39e, dn: 0xbebc200000000000, v: 0x5798ee2308c39df9, p: 11, s: 37},           // k = 8
	{d: 1000000000, m: 0x0089705f4136b4a6, dn: 0xee6b280000000000, v: 0x12e0be826d694b2e, p: 12, s: 34},          // k = 9
	{d: 10000000000, m: 0x006df37f675ef6eb, dn: 0x9502f90000000000, v: 0xb7cdfd9d7bdbab7d, p: 14, s: 30},         // k = 10
	{d: 100000000000, m: 0x002bfaffc2f2c92b, dn: 0xba43b74000000000, v: 0x5fd7fe17964955fd, p: 15, s: 27},        // k = 11
	{d: 1000000000000, m: 0x00119799812dea12, dn: 0xe8d4a51000000000, v: 0x19799812dea11197, p: 16, s: 24},       // k = 12
	{d: 10000000000000, m: 0x000e12e13424bb41, dn: 0x9184e72a00000000, v: 0xc25c268497681c26, p: 18, s: 20},      // k = 13
	{d: 100000000000000, m: 0x0005a126e1a84ae7, dn: 0xb5e620f480000000, v: 0x6849b86a12b9b01e, p: 19, s: 17},     // k = 14
	{d: 1000000000000000, m: 0x00024075f3dceac3, dn: 0xe35fa931a0000000, v: 0x203af9ee756159b2, p: 20, s: 14},    // k = 15
	{d: 10000000000000000, m: 0x0001cd2b297d889c, dn: 0x8e1bc9bf04000000, v: 0xcd2b297d889bc2b6, p: 22, s: 10},   // k = 16
	{d: 100000000000000000, m: 0x0000b877aa3236a5, dn: 0xb1a2bc2ec5000000, v: 0x70ef54646d496892, p: 23, s: 7},   // k = 17
	{d: 1000000000000000000, m: 0x000049c97747490f, dn: 0xde0b6b3a76400000, v: 0x2725dd1d243aba0e, p: 24, s: 4},  // k = 18
	{d: 10000000000000000000, m: 0x00003b07929f6da6, dn: 0x8ac7230489e80000, v: 0xd83c94fb6d2ac34a, p: 26, s: 0}, // k = 19
}

// pow10u64 holds 10^k for k = 0..19; entries 20..31 stay zero, padding the
// array to a power of two for bounds-check-free indexing.
var pow10u64 = [32]uint64{
	1,                    // 10^0
	10,                   // 10^1
	100,                  // 10^2
	1000,                 // 10^3
	10000,                // 10^4
	100000,               // 10^5
	1000000,              // 10^6
	10000000,             // 10^7
	100000000,            // 10^8
	1000000000,           // 10^9
	10000000000,          // 10^10
	100000000000,         // 10^11
	1000000000000,        // 10^12
	10000000000000,       // 10^13
	100000000000000,      // 10^14
	1000000000000000,     // 10^15
	10000000000000000,    // 10^16
	100000000000000000,   // 10^17
	1000000000000000000,  // 10^18
	10000000000000000000, // 10^19
}

// pow10u128 holds 10^k for k = 0..38 — the full range of precision-product
// scale factors; entries 39..63 stay zero, padding the array to a power of
// two for bounds-check-free indexing.
var pow10u128 = [64]u128{
	{lo: 1},                    // 10^0
	{lo: 10},                   // 10^1
	{lo: 100},                  // 10^2
	{lo: 1000},                 // 10^3
	{lo: 10000},                // 10^4
	{lo: 100000},               // 10^5
	{lo: 1000000},              // 10^6
	{lo: 10000000},             // 10^7
	{lo: 100000000},            // 10^8
	{lo: 1000000000},           // 10^9
	{lo: 10000000000},          // 10^10
	{lo: 100000000000},         // 10^11
	{lo: 1000000000000},        // 10^12
	{lo: 10000000000000},       // 10^13
	{lo: 100000000000000},      // 10^14
	{lo: 1000000000000000},     // 10^15
	{lo: 10000000000000000},    // 10^16
	{lo: 100000000000000000},   // 10^17
	{lo: 1000000000000000000},  // 10^18
	{lo: 10000000000000000000}, // 10^19
	{hi: 0x0000000000000005, lo: 0x6bc75e2d63100000}, // 10^20
	{hi: 0x0000000000000036, lo: 0x35c9adc5dea00000}, // 10^21
	{hi: 0x000000000000021e, lo: 0x19e0c9bab2400000}, // 10^22
	{hi: 0x000000000000152d, lo: 0x02c7e14af6800000}, // 10^23
	{hi: 0x000000000000d3c2, lo: 0x1bcecceda1000000}, // 10^24
	{hi: 0x0000000000084595, lo: 0x161401484a000000}, // 10^25
	{hi: 0x000000000052b7d2, lo: 0xdcc80cd2e4000000}, // 10^26
	{hi: 0x00000000033b2e3c, lo: 0x9fd0803ce8000000}, // 10^27
	{hi: 0x00000000204fce5e, lo: 0x3e25026110000000}, // 10^28
	{hi: 0x00000001431e0fae, lo: 0x6d7217caa0000000}, // 10^29
	{hi: 0x0000000c9f2c9cd0, lo: 0x4674edea40000000}, // 10^30
	{hi: 0x0000007e37be2022, lo: 0xc0914b2680000000}, // 10^31
	{hi: 0x000004ee2d6d415b, lo: 0x85acef8100000000}, // 10^32
	{hi: 0x0000314dc6448d93, lo: 0x38c15b0a00000000}, // 10^33
	{hi: 0x0001ed09bead87c0, lo: 0x378d8e6400000000}, // 10^34
	{hi: 0x0013426172c74d82, lo: 0x2b878fe800000000}, // 10^35
	{hi: 0x00c097ce7bc90715, lo: 0xb34b9f1000000000}, // 10^36
	{hi: 0x0785ee10d5da46d9, lo: 0x00f436a000000000}, // 10^37
	{hi: 0x4b3b4ca85a86c47a, lo: 0x098a224000000000}, // 10^38
}
